import Leadership from "../component/principleDesk/Leadership";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Principal & Leadership - Saket MGM School",
  description:
    "Meet the leadership team of Saket MGM School, including the Principal, Vice-Principals, and other key administrative members. Learn about their vision, experience, and contributions to the school community.",
  keywords: [
    "Saket MGM School Principal",
    "School Leadership",
    "School Administration",
    "CBSE School Leaders",
    "Principal Profile",
    "Vice Principal",
    "School Management",
    "Educational Leadership",
    "Academic Administration",
    "School Vision",
    "School Mission",
    "Leadership Team",
    "Saket MGM School Staff",
    "Education Management",
    "Principal Message",
    "Administrative Team",
    "Educational Excellence",
    "School Governance",
    "Head of School",
    "School Policies",
    "Teacher Coordination",
    "Student Affairs",
    "School Programs",
    "Extracurricular Leadership",
    "Academic Planning",
    "Staff Development",
    "School Achievements",
    "Principal Initiatives",
    "School Events Leadership",
    "Student Engagement",
    "Parental Communication",
    "Community Outreach",
    "Curriculum Oversight",
    "Education Standards",
    "Leadership Philosophy",
    "School Improvement",
    "Staff Motivation",
    "Educational Guidance",
    "Principal Vision Statement",
    "CBSE Compliance",
    "School Mission Statement",
    "Student Welfare",
    "Teacher Support",
    "School Development",
    "Campus Management",
    "School Safety",
    "Academic Coordination",
    "Education Strategies",
    "Leadership Communication",
    "Visionary Education",
    "Educational Policies",
    "School Governance Team",
    "Principal Leadership Style",
    "Administration Strategies",
    "School Planning",
    "Student-Centered Leadership",
    "Educational Initiatives",
    "Campus Excellence",
    "Academic Leadership",
    "Principal Achievements",
    "Leadership Excellence",
    "Teacher Leadership",
    "School Management Team",
    "Principal Experience",
    "Saket MGM Leadership Team",
    "Principal Message to Parents",
    "Educational Visionary",
    "School Administration Excellence",
    "Student Success Initiatives",
    "Leadership in Education",
    "Principal Engagement",
    "School Quality Management",
    "Principal Profile Saket MGM",
    "School Management Excellence",
    "Leadership in CBSE School",
    "Principal's Role",
    "Educational Leadership Team",
    "Principal Guidance",
    "Teacher Coordination Leadership",
    "School Administration Policies",
    "Leadership Communication Skills",
    "Principal Vision Education",
    "School Academic Planning",
    "Educational Achievements",
    "Principal Responsibilities",
    "School Leadership Goals",
    "Student Development Leadership",
    "Principal and Staff",
    "Principal Messages",
    "School Administration Updates",
    "Leadership Best Practices",
    "Principal Initiatives Saket MGM",
    "Educational Vision Saket MGM",
    "Leadership in School Administration",
  ],
  authors: [{ name: "Saket MGM School", url: "https://www.saketmgm.com" }],
  creator: "Saket MGM School",
  publisher: "Saket MGM School",
  metadataBase: new URL("https://www.saketmgm.com"),
  openGraph: {
    type: "website",
    title: "Principal & Leadership - Saket MGM School",
    description:
      "Meet the leadership team of Saket MGM School, including the Principal, Vice-Principals, and other key administrative members. Learn about their vision, experience, and contributions to the school community.",
    url: "https://www.saketmgm.com/principal",
    siteName: "Saket MGM School",
    images: [
      {
        url: "/logo.png",
        width: 800,
        height: 600,
        alt: "Saket MGM School Logo",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "Principal & Leadership - Saket MGM School",
    description:
      "Meet the leadership team of Saket MGM School, including the Principal, Vice-Principals, and other key administrative members. Learn about their vision, experience, and contributions to the school community.",
    creator: "@saketmgmschool",
    images: ["/logo.png"],
  },
  icons: {
    icon: "/logo.png",
    shortcut: "/logo.png",
    apple: "/logo.png",
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
    },
  },
};

export default function PrincipalPage() {
  return <Leadership />;
}
